# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowPaint.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowPaint(object):
    def setupUi(self, MainWindowPaint):
        MainWindowPaint.setObjectName("MainWindowPaint")
        MainWindowPaint.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindowPaint)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_2.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_Dibujar = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Dibujar.setObjectName("pushButton_Dibujar")
        self.gridLayout_3.addWidget(self.pushButton_Dibujar, 0, 0, 1, 1)
        self.pushButton_Borrar = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Borrar.setObjectName("pushButton_Borrar")
        self.gridLayout_3.addWidget(self.pushButton_Borrar, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(21)
        self.horizontalSlider.setSingleStep(2)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_4.addWidget(self.horizontalSlider, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.pushButton_Exportar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Exportar.setObjectName("pushButton_Exportar")
        self.verticalLayout_2.addWidget(self.pushButton_Exportar)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.setStretch(0, 10)
        self.horizontalLayout_2.setStretch(1, 2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        MainWindowPaint.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindowPaint)
        self.statusbar.setObjectName("statusbar")
        MainWindowPaint.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowPaint)
        QtCore.QMetaObject.connectSlotsByName(MainWindowPaint)

    def retranslateUi(self, MainWindowPaint):
        _translate = QtCore.QCoreApplication.translate
        MainWindowPaint.setWindowTitle(_translate("MainWindowPaint", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindowPaint", "ACCIONES"))
        self.pushButton_Dibujar.setText(_translate("MainWindowPaint", "Dibujar"))
        self.pushButton_Borrar.setText(_translate("MainWindowPaint", "Borrar"))
        self.groupBox_2.setTitle(_translate("MainWindowPaint", "Scale"))
        self.label.setText(_translate("MainWindowPaint", "Pixel Size"))
        self.pushButton_Exportar.setText(_translate("MainWindowPaint", "EXPORTAR"))
