# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindowPaint.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WindowPaint(object):
    def setupUi(self, WindowPaint):
        WindowPaint.setObjectName("WindowPaint")
        WindowPaint.resize(1920, 1080)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(WindowPaint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(WindowPaint)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.groupBox = QtWidgets.QGroupBox(WindowPaint)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_Dibujar = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Dibujar.setObjectName("pushButton_Dibujar")
        self.verticalLayout_3.addWidget(self.pushButton_Dibujar)
        self.pushButton_Borrar = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Borrar.setObjectName("pushButton_Borrar")
        self.verticalLayout_3.addWidget(self.pushButton_Borrar)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.groupBox_2 = QtWidgets.QGroupBox(WindowPaint)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(21)
        self.horizontalSlider.setSingleStep(2)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider.setTickInterval(2)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_4.addWidget(self.horizontalSlider)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.pushButton_Exportar = QtWidgets.QPushButton(WindowPaint)
        self.pushButton_Exportar.setObjectName("pushButton_Exportar")
        self.verticalLayout.addWidget(self.pushButton_Exportar)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2.setStretch(0, 10)
        self.horizontalLayout_2.setStretch(1, 2)

        self.retranslateUi(WindowPaint)
        QtCore.QMetaObject.connectSlotsByName(WindowPaint)

    def retranslateUi(self, WindowPaint):
        _translate = QtCore.QCoreApplication.translate
        WindowPaint.setWindowTitle(_translate("WindowPaint", "Form"))
        self.groupBox.setTitle(_translate("WindowPaint", "ACCIONES"))
        self.pushButton_Dibujar.setText(_translate("WindowPaint", "Dibujar"))
        self.pushButton_Borrar.setText(_translate("WindowPaint", "Borrar"))
        self.groupBox_2.setTitle(_translate("WindowPaint", "SCALE"))
        self.label.setText(_translate("WindowPaint", "Pixel Size"))
        self.pushButton_Exportar.setText(_translate("WindowPaint", "EXPORTAR"))
